[package]
edition = "2021"
name = "x-win"
version = "0.1.0"
authors = ["BENKHADRA Hocine <miniben90@hotmail.com>"]
keywords = ["window", "active", "current", "position", "title", "list", "open"]
description = "Get position, size, title and a few other properties of the active or open window(s) on Windows, MacOS and Linux."
repository = "https://github.com/miniben-90/x-win"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.10.3", default-features = false, features = ["napi4"] }
napi-derive = "2.9.3"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.43.0", features = [
  "Win32_Foundation",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_Threading",
  "Win32_Storage_FileSystem",
  "Win32_System_ProcessStatus",
  "Win32_System_StationsAndDesktops",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_Graphics_Dwm"
]}

[target.'cfg(target_os = "linux")'.dependencies]
xcb = "1.2"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24.1"
libc = "0.2.139"
cocoa-foundation = "0.1"
core-foundation = "0.9.3"
core-foundation-sys = "0.8.3"
core-graphics = "0.22.3"
objc = "0.2.7"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
